base_url = "https://lucasnasm.github.io"
compile_sass = false
title = "nasm-theme"
description = "Blog"
build_search_index = false
default_language = "pt"

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "Lucas"
disqus_username = ""
ganalytics = ""
nasm_menu = [
    {url = "$BASE_URL", name = "Home", fawesome = "fas fa-home"},
    {url = "$BASE_URL/categories", name = "Categories", fawesome = "fas fa-folder-open"},
    {url = "$BASE_URL/tags", name = "Tags", fawesome = "fas fa-tag" },
    {url = "$BASE_URL/about", name = "About", fawesome = "fas fa-user-alt" },

]
nasm_title = "Posts"
