base_url = "https://lucasnasm.github.io"
compile_sass = false
title = "nasm-theme"
description = "Blog"

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "Lucas"
disqus_username = ""
nasm_menu = [
    {url = "$BASE_URL", name = "Home", fawesome = "fas fa-home"},
    {url = "$BASE_URL/categories", name = "Categorias", fawesome = "fas fa-folder-open"},
    {url = "$BASE_URL/tags", name = "Tags", fawesome = "fas fa-tag" },
    {url = "$BASE_URL/about", name = "Sobre", fawesome = "fas fa-user-alt" },

]
nasm_title = "Post recentes"
