name = "nasm-theme"
description = "A robust, elegant blue theme"
license = "MIT"
homepage = "https://github.com/lucasnasm/nasm-theme"
min_version = "0.1.0"
demo = "https://lucasnasm.github.io"

[extra]


[author]
name = "Francisco Lucas"
homepage = "https://lucasnasm.github.io"

[original]
name = "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"
repo = "https://github.com/getzola/after-dark/"
